using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Content.Shared.DeadSpace.GhostRoleNotify.Prototypes;
using Robust.Shared.Prototypes;

namespace Content.Client.Options.UI.Tabs;

[GenerateTypedNameReferences]

public sealed partial class PingTab : Control
{
    List<bool> _roles = new List<bool>();
    int _numberForButton = 0;
    //[Dependency] private readonly IPrototypeManager _prototypes = default!;

    void Lolalaoalalal()
    {
        for (int i = 0; i < 60; i++)
        {
            _roles.Add(false);
        }
    }

    private void AddCheckBox(string checkBoxName, int number)
    {
        CheckBox newCheckBox = new CheckBox() { Text = Loc.GetString(checkBoxName) };
        newCheckBox.Pressed = _roles[number];
        newCheckBox.OnToggled += (lol) =>
        {
            _roles[number] = newCheckBox.Pressed;
        };

        PingsCont.AddChild(newCheckBox);
    }
    public PingTab()
    {
        var prototypeManager = IoCManager.Resolve<IPrototypeManager>();
        Lolalaoalalal();
        RobustXamlLoader.Load(this);
        foreach (var proto in prototypeManager.EnumeratePrototypes<GhostRoleGroupNotify>())
        {
            AddCheckBox(proto.Name, _numberForButton);
            _numberForButton += 1;
        }
        Control.Initialize();
    }
}