using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Content.Shared.DeadSpace.GhostRoleNotify.Prototypes;
using Robust.Shared.Prototypes;
using Robust.Shared.Configuration;

namespace Content.Client.Options.UI.Tabs;

[GenerateTypedNameReferences]

public sealed partial class PingTab : Control
{
    [Dependency] private readonly IConfigurationManager _cfg = default!;
    public static Dictionary<string, bool> _dictAccess = new Dictionary<string, bool>();
    public static bool GetValueAccess(string key)
    {
        if (key == null)
        {
            return false;
        }
        if (_dictAccess.TryGetValue(key, out bool value))
        {
            return value;
        }
        else
        {
            // Поведение, если ключ не найден — например, бросить исключение или вернуть false
            return false;
        }
    }

    private void AddCheckBox(string checkBoxName, string id)
    {
        CheckBox newCheckBox = new CheckBox() { Text = Loc.GetString(checkBoxName) };
        newCheckBox.Pressed = false;
        newCheckBox.OnToggled += (lol) =>
        {
            _dictAccess[id] = newCheckBox.Pressed;
        };

        PingsCont.AddChild(newCheckBox);
    }
    public PingTab()
    {
        var prototypeManager = IoCManager.Resolve<IPrototypeManager>();
        RobustXamlLoader.Load(this);
        foreach (var proto in prototypeManager.EnumeratePrototypes<GhostRoleGroupNotify>())
        {
            _dictAccess.Add(proto.ID, false);
            AddCheckBox(proto.Name, proto.ID);
        }
        Control.Initialize();
    }
}
