// Мёртвый Космос, Licensed under custom terms with restrictions on public hosting and commercial use, full text: https://raw.githubusercontent.com/dead-space-server/space-station-14-fobos/master/LICENSE.TXT
using Content.Shared.DeadSpace.Administration.Events;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Administration.UI;

[GenerateTypedNameReferences]
public sealed partial class AdminGlobalSoundWindow : DefaultWindow
{
    private string? _selectedFile;
    private string? _currentPath;

    public event Action<AdminGlobalSoundEuiMessage.Browse>? BrowseRequested;
    public event Action<AdminGlobalSoundEuiMessage.Play>? PlayRequested;
    public event Action<AdminGlobalSoundControl>? ControlRequested;

    public AdminGlobalSoundWindow()
    {
        RobustXamlLoader.Load(this);
        PlayButton.OnPressed += OnPlayPressed;
        PauseButton.OnPressed += _ => ControlRequested?.Invoke(AdminGlobalSoundControl.Pause);
        ResumeButton.OnPressed += _ => ControlRequested?.Invoke(AdminGlobalSoundControl.Resume);
        FadeButton.OnPressed += _ => ControlRequested?.Invoke(AdminGlobalSoundControl.FadeOut);
    }

    public void UpdateState(AdminGlobalSoundEuiState state)
    {
        if (_currentPath != state.CurrentPath)
            _selectedFile = null;
        _currentPath = state.CurrentPath;
        CurrentPath.Text = state.CurrentPath;
        CurrentTrack.Text = state.CurrentTrack is { } track
            ? Loc.GetString("admin-global-sound-playing", ("track", track))
            : Loc.GetString("admin-global-sound-nothing-playing");
        Error.Text = state.Error ?? "";
        PauseButton.Disabled = state.CurrentTrack == null || state.Paused;
        ResumeButton.Disabled = state.CurrentTrack == null || !state.Paused;
        FadeButton.Disabled = state.CurrentTrack == null;
        SelectedFile.Text = _selectedFile ?? Loc.GetString("admin-global-sound-no-selection");

        Entries.RemoveAllChildren();
        foreach (var entry in state.Entries)
        {
            var button = new Button
            {
                Text = entry.IsDirectory ? $"[+] {entry.Name}" : entry.Name,
                HorizontalExpand = true,
                TextAlign = Label.AlignMode.Left,
            };

            button.OnPressed += _ =>
            {
                if (entry.IsDirectory)
                {
                    BrowseRequested?.Invoke(new AdminGlobalSoundEuiMessage.Browse { Path = entry.Path });
                    return;
                }

                _selectedFile = entry.Path;
                SelectedFile.Text = entry.Path;
            };
            Entries.AddChild(button);
        }
    }

    private void OnPlayPressed(BaseButton.ButtonEventArgs args)
    {
        if (_selectedFile == null)
        {
            Error.Text = Loc.GetString("admin-global-sound-no-selection");
            return;
        }

        if (!int.TryParse(Volume.Text, System.Globalization.NumberStyles.Integer,
                System.Globalization.CultureInfo.InvariantCulture, out var volume) ||
            volume is < -24 or > 12)
        {
            Error.Text = Loc.GetString("admin-global-sound-invalid-volume");
            return;
        }

        PlayRequested?.Invoke(new AdminGlobalSoundEuiMessage.Play
        {
            Path = _selectedFile,
            Volume = volume,
            CKey = CKey.Text,
        });
    }
}
