using System.Linq;
using Content.Shared.Administration;
using Content.Shared.Corvax.TTS;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;

namespace Content.Client.Administration.UI
{
    [GenerateTypedNameReferences]
    public sealed partial class AdminAnnounceWindow : DefaultWindow
    {
        [Dependency] private readonly ILocalizationManager _localization = default!;

        private readonly List<TTSVoicePrototype> _voices; // Corvax-TTS
        public Action<string>? OnVoiceChange; // Corvax-TTS

        private LineEdit _colorHexEdit; // DS14-announce
        private Button _colorPreviewBtn; // DS14-announce
        private LineEdit _soundPathEdit; // DS14-announce
        private LineEdit _soundVolumeEdit; // DS14-announce
        private LineEdit _senderEdit; // DS14-announce

        public AdminAnnounceWindow()
        {
            RobustXamlLoader.Load(this);
            IoCManager.InjectDependencies(this);

            // DS14-announce-start
            _colorHexEdit = FindControl<LineEdit>("ColorHex");
            _colorPreviewBtn = FindControl<Button>("ColorPreview");
            _soundPathEdit = FindControl<LineEdit>("SoundPath");
            _soundVolumeEdit = FindControl<LineEdit>("SoundVolume");
            _senderEdit = FindControl<LineEdit>("Sender");
            _colorHexEdit.OnTextChanged += OnColorTextChanged;
            UpdateColorPreview();
            // DS14-announce-end

            Announcement.Placeholder =
                new Rope.Leaf(_localization.GetString("admin-announce-announcement-placeholder"));
            AnnounceMethod.AddItem(_localization.GetString("admin-announce-type-station"));
            AnnounceMethod.SetItemMetadata(0, AdminAnnounceType.Station);
            AnnounceMethod.AddItem(_localization.GetString("admin-announce-type-server"));
            AnnounceMethod.SetItemMetadata(1, AdminAnnounceType.Server);
            AnnounceMethod.OnItemSelected += AnnounceMethodOnOnItemSelected;
            VoiceSelector.OnItemSelected += AnnounceMethodOnOnTTSItemSelected;
            Announcement.OnKeyBindUp += AnnouncementOnOnTextChanged;

            // Corvax-TTS-Start
            _voices = IoCManager
                .Resolve<IPrototypeManager>()
                .EnumeratePrototypes<TTSVoicePrototype>()
                .OrderBy(o => Loc.GetString(o.Name))
                .ToList();
            for (var i = 0; i < _voices.Count; i++)
            {
                var name = Loc.GetString(_voices[i].Name);
                VoiceSelector.AddItem(name);
                VoiceSelector.SetItemMetadata(i, _voices[i].ID);
            }
            // Corvax-TTS-End
        }

        // DS14-announce-start
        private void OnColorTextChanged(LineEdit.LineEditEventArgs args)
        {
            UpdateColorPreview();
        }

        private void UpdateColorPreview()
        {
            try
            {
                var color = Color.FromHex(_colorHexEdit.Text);
                _colorPreviewBtn.ModulateSelfOverride = color;
            }
            catch
            {
                _colorPreviewBtn.ModulateSelfOverride = null;
            }
        }

        public string ColorHexText => _colorHexEdit.Text;
        public string SoundPathText => _soundPathEdit.Text;
        public string SenderText => _senderEdit.Text;
        public float SoundVolumeValue
        {
            get
            {
                if (float.TryParse(_soundVolumeEdit.Text, out var volume))
                    return Math.Clamp(volume, 1f, 10f);
                return 5f;
            }
        }
        // DS14-announce-end

        private void AnnouncementOnOnTextChanged(GUIBoundKeyEventArgs args)
        {
            AnnounceButton.Disabled = Rope.Collapse(Announcement.TextRope).TrimStart() == "";
        }

        private void AnnounceMethodOnOnItemSelected(OptionButton.ItemSelectedEventArgs args)
        {
            AnnounceMethod.SelectId(args.Id);
            Announcer.Editable = ((AdminAnnounceType?)args.Button.SelectedMetadata ?? AdminAnnounceType.Station) ==
                                 AdminAnnounceType.Station;
        }

        // Corvax-TTS-Start
        private void AnnounceMethodOnOnTTSItemSelected(OptionButton.ItemSelectedEventArgs args)
        {
            VoiceSelector.SelectId(args.Id);
        }
        // Corvax-TTS-End
    }
}
