- files: ["weh_pop.ogg",]
  license: "CC0-1.0"
  copyright: "Created by BlackMajor (github) for ss14, muffled_weh.ogg modified from weh.ogg by Slorkito (ss14 discord), added SFX POPCAT"
  source: "https://github.com/space-wizards/space-station-14/blob/master/Resources/Audio/Items/Toys/weh.ogg"