// Мёртвый Космос, Licensed under custom terms with restrictions on public hosting and commercial use, full text: https://raw.githubusercontent.com/dead-space-server/space-station-14-fobos/master/LICENSE.TXT

using System;
using System.Numerics;
using Content.Shared.DeadSpace.Ninja;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.GameObjects;
using Robust.Shared.IoC;
using Robust.Shared.Localization;

namespace Content.Client.DeadSpace.Ninja.UI;

[GenerateTypedNameReferences]
public sealed partial class NinjaInfoScannerWindow : DefaultWindow
{
    [Dependency] private readonly IEntityManager _entityManager = default!;

    public event Action? OnScanPressed;
    public event Action? OnEjectPressed;
    public event Action? OnTeleportPressed;

    public NinjaInfoScannerWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        TargetView.Scale = new Vector2(2.5f, 2.5f);

        ScanButton.OnPressed += _ => OnScanPressed?.Invoke();
        EjectButton.OnPressed += _ => OnEjectPressed?.Invoke();
        TeleportButton.OnPressed += _ => OnTeleportPressed?.Invoke();
    }

    public void UpdateState(NinjaInfoScannerState state)
    {
        if (state.ContainedEntity is { } netEntity)
        {
            var entity = _entityManager.GetEntity(netEntity);
            TargetView.SetEntity(entity);

            var entityName = _entityManager.EntityExists(entity)
                ? _entityManager.GetComponent<MetaDataComponent>(entity).EntityName
                : Loc.GetString("ninja-info-job-unknown");

            StatusLabel.Text = Loc.GetString("ninja-info-ui-status-subject", ("name", entityName));

            ScanButton.Disabled = false;
            EjectButton.Disabled = false;
            TeleportButton.Disabled = false;
        }
        else
        {
            TargetView.SetEntity(null);
            StatusLabel.Text = Loc.GetString("ninja-info-ui-status-empty");

            ScanButton.Disabled = true;
            EjectButton.Disabled = true;
            TeleportButton.Disabled = true;
        }
    }
}