// Мёртвый Космос, Licensed under custom terms with restrictions on public hosting and commercial use, full text: https://raw.githubusercontent.com/dead-space-server/space-station-14-fobos/master/LICENSE.TXT

using System.Linq;
using System.Numerics;
using Content.Client.Clothing;
using Content.Client.Humanoid;
using Content.Shared.Clothing.Components;
using Content.Shared.DeadSpace.Ninja;
using Content.Shared.Humanoid;
using Content.Shared.Humanoid.Prototypes;
using Content.Shared.Inventory;
using Content.Shared.StatusIcon;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Content.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Map;
using Robust.Shared.Prototypes;
using Content.Client.DeadSpace.Stylesheets;
using Content.Shared.DeadSpace.Ninja.Systems;

namespace Content.Client.DeadSpace.Ninja.UI;

[GenerateTypedNameReferences]
public sealed partial class NinjaDisguiseWindow : FancyWindow
{
    [Dependency] private readonly IEntityManager _entManager = default!;
    [Dependency] private readonly IPrototypeManager _proto = default!;

    private readonly SpriteSystem _spriteSystem;
    private readonly HumanoidAppearanceSystem _humanoid;
    private readonly ClientClothingSystem _clothingSystem;
    private readonly InventorySystem _inventorySystem;
    private readonly SharedNinjaDisguiseSystem _ninjaDisguiseSystem = default!;

    private readonly List<EntityUid> _previews = new();

    public event Action<int>? OnApplyEntry;
    public event Action? OnResetPressed;

    public NinjaDisguiseWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        AddStyleClass(DeadSpaceStyleClass.SpiderOSWindow);
        HeaderClass = DeadSpaceStyleClass.SpiderOSWindowHeader;

        _spriteSystem = _entManager.System<SpriteSystem>();
        _humanoid = _entManager.System<HumanoidAppearanceSystem>();
        _clothingSystem = _entManager.System<ClientClothingSystem>();
        _inventorySystem = _entManager.System<InventorySystem>();
        _ninjaDisguiseSystem = _entManager.System<SharedNinjaDisguiseSystem>();

        ResetButton.OnPressed += _ => OnResetPressed?.Invoke();

        OnClose += HandleClose;
    }

    public void UpdateState(NinjaDisguiseState state)
    {
        CleanupPreviews();
        EntriesContainer.RemoveAllChildren();

        EmptyLabel.Visible = state.Entries.Count == 0;

        for (var i = 0; i < state.Entries.Count; i++)
        {
            var index = i;
            EntriesContainer.AddChild(BuildEntryRow(state.Entries[i], state, index));
        }

        ResetButton.Disabled = !state.Disguised;
    }

    private Control BuildEntryRow(NinjaDisguiseEntry entry, NinjaDisguiseState state, int index)
    {
        var row = new Button();

        var horizontal = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            SeparationOverride = 8,
        };

        var preview = new SpriteView { Scale = new Vector2(2, 2) };
        var previewEntity = CreatePreviewEntity(entry);
        if (previewEntity != null)
            preview.SetEntity(previewEntity);

        horizontal.AddChild(preview);

        var info = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Vertical,
            VerticalExpand = true,
            SeparationOverride = 2,
        };

        var nameLabel = new Label { Text = entry.Name };
        if (!string.IsNullOrWhiteSpace(entry.Description))
            nameLabel.ToolTip = entry.Description;
        info.AddChild(nameLabel);

        var jobBox = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            SeparationOverride = 4,
        };

        var noIdCard = !entry.HasIdCard;

        ProtoId<JobIconPrototype> jobIconId = entry.JobIcon;
        if (noIdCard)
            jobIconId = "JobIconNoId";

        if (_proto.TryIndex<JobIconPrototype>(jobIconId, out var jobIcon))
        {
            jobBox.AddChild(new TextureRect
            {
                Texture = _spriteSystem.Frame0(jobIcon.Icon),
                TextureScale = new Vector2(2, 2),
                VerticalAlignment = VAlignment.Center,
            });
        }

        if (noIdCard)
            jobBox.AddChild(new Label { Text = Loc.GetString("ninja-disguise-ui-no-data") });
        else if (!string.IsNullOrWhiteSpace(entry.JobTitle))
            jobBox.AddChild(new Label { Text = entry.JobTitle });

        if (jobBox.ChildCount > 0)
            info.AddChild(jobBox);

        if (state.ActiveIndex == index)
            info.AddChild(new Label { Text = Loc.GetString("ninja-disguise-ui-active") });

        horizontal.AddChild(info);
        row.AddChild(horizontal);

        var capturedIndex = index;
        row.OnPressed += _ => OnApplyEntry?.Invoke(capturedIndex);

        return row;
    }

    private EntityUid? CreatePreviewEntity(NinjaDisguiseEntry entry)
    {
        try
        {
            if (entry.Appearance is not { } appearance ||
                !_proto.TryIndex<SpeciesPrototype>(appearance.Species, out var species))
            {
                return null;
            }

            var uid = _entManager.SpawnEntity(species.DollPrototype, MapCoordinates.Nullspace);
            if (!_entManager.TryGetComponent<HumanoidAppearanceComponent>(uid, out var humanoid) ||
                !_entManager.TryGetComponent<SpriteComponent>(uid, out _))
            {
                _entManager.DeleteEntity(uid);
                return null;
            }

            _ninjaDisguiseSystem.ApplyAppearance((uid, humanoid), appearance);

            _inventorySystem.SetInventorySpecies(uid, entry.InventorySpeciesId ?? appearance.Species.Id);

            _humanoid.RefreshAppearance(uid, humanoid);

            foreach (var inventoryEntry in entry.Inventory)
            {
                if (!_proto.HasIndex<EntityPrototype>(inventoryEntry.ItemId))
                    continue;

                if (entry.HiddenClothingSlots.Contains(inventoryEntry.Slot, StringComparer.OrdinalIgnoreCase))
                    continue;

                var proxyUid = _entManager.SpawnEntity(inventoryEntry.ItemId, MapCoordinates.Nullspace);
                if (!_entManager.HasComponent<ClothingComponent>(proxyUid))
                {
                    _entManager.DeleteEntity(proxyUid);
                    continue;
                }

                _clothingSystem.RenderEquipment(uid, proxyUid, inventoryEntry.Slot, slotOffset: inventoryEntry.SlotOffset);
                _previews.Add(proxyUid);
            }

            _previews.Add(uid);
            return uid;
        }
        catch (Exception e)
        {
            Log.Error($"Failed to build ninja disguise preview: {e}");
            return null;
        }
    }

    private void CleanupPreviews()
    {
        foreach (var uid in _previews)
        {
            if (_entManager.EntityExists(uid))
                _entManager.DeleteEntity(uid);
        }

        _previews.Clear();
    }

    private void HandleClose()
    {
        CleanupPreviews();
    }
}