// Мёртвый Космос, Licensed under custom terms with restrictions on public hosting and commercial use, full text: https://raw.githubusercontent.com/dead-space-server/space-station-14-fobos/master/LICENSE.TXT

using Content.Client.UserInterface.Controls;
using Content.Shared.DeadSpace.RadioSettings;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.DeadSpace.RadioSettings;

[GenerateTypedNameReferences]
public sealed partial class RadioSettingsWindow : FancyWindow
{
    public event Action<RadioMode, bool>? OnRadioSettingsButton;

    public RadioSettingsWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        ListeningButton.OnPressed += _ =>
        {
            ListeningButton.Pressed = !ListeningButton.Pressed;
            OnRadioSettingsButton?.Invoke(RadioMode.Listening,  ListeningButton.Pressed);
        };

        SpeakingButton.OnPressed += _ =>
        {
            SpeakingButton.Pressed = !SpeakingButton.Pressed;
            OnRadioSettingsButton?.Invoke(RadioMode.Speaking,  SpeakingButton.Pressed);
        };
    }
    public void UpdateState(BoundUserInterfaceState state)
    {
        var castState = (RadioSettingsState) state;

        ListeningButton.Pressed = castState.ListeningMode.IsToggle;
        SpeakingButton.Pressed = castState.SpeakingMode.IsToggle;
    }
}
