using Content.Client.UserInterface.Controls;
using Rgba32 = SixLabors.ImageSharp.PixelFormats.Rgba32;
using SixLabors.ImageSharp.PixelFormats;
using Robust.Shared.ContentPack;
using Robust.Client.Utility;
using Content.Shared.DeadSpace.PdaPainter;
using Content.Shared.PDA;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using System.Numerics;
using Robust.Shared.Map;
using Robust.Shared.Maths;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;

namespace Content.Client.DeadSpace.PdaPainter.UI;

[GenerateTypedNameReferences]
public sealed partial class PdaPainterWindow : DefaultWindow
{
    private static readonly Color[] Palette =
    {
        Color.Red,
        Color.Orange,
        Color.Yellow,
        Color.Green,
        Color.Cyan,
        Color.Blue,
        Color.Purple,
        Color.White,
        Color.Black,
    };

    private static readonly Color UnselectedBorder = Color.FromHex("#222222");
    private static readonly Color SelectedBorder = Color.FromHex("#ffd35c");

    public event Action<List<int>, List<int>>? OnPixelsDrawn;
    public event Action<string?>? OnSavePressed;
    public event Action? OnResetPressed;

    [Dependency] private readonly IEntityManager _entMan = default!;
    [Dependency] private readonly IPrototypeManager _proto = default!;
    [Dependency] private readonly IResourceManager _resMan = default!;

    private readonly SpriteSystem _spriteSystem;
    private readonly SharedAppearanceSystem _appearance;

    private Color _currentColor = Palette[0];
    private int _selectedPaletteIndex;
    private PdaPainterTool _tool = PdaPainterTool.Brush;
    private string? _selectedTemplate;
    private string? _previewProtoId;
    private readonly List<PdaPainterTemplateInfo> _allTemplates = new();
    private readonly List<string> _templateIds = new();
    private readonly Dictionary<string, (string? Rsi, string? State)> _templateRsi = new();
    private readonly Dictionary<string, Texture?> _templateIcons = new();

    private readonly Dictionary<int, int> _pixels = new();
    private readonly Dictionary<int, Button> _paletteButtons = new();
    private readonly Dictionary<int, StyleBoxFlat> _paletteStyles = new();
    private readonly Dictionary<string, Dictionary<int, int>?> _pixelMapCache = new();
    private Dictionary<int, int>? _previewPixelMap;
    private Dictionary<int, int>? _templatePixelMap;
    private bool _populated;

    private static readonly Color Highlight = new(1.35f, 1.35f, 1.15f);

    public PdaPainterWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _spriteSystem = _entMan.System<SpriteSystem>();
        _appearance = _entMan.System<SharedAppearanceSystem>();

        Tabs.SetTabTitle(0, Loc.GetString("pda-painter-tab-free"));
        Tabs.SetTabTitle(1, Loc.GetString("pda-painter-tab-template"));

        PopulatePalette();
        WireCanvas(FreeCanvas);
        WireCanvas(TemplateCanvas);

        ColorPicker.OnColorChanged += color =>
        {
            _currentColor = color;

            if (_selectedPaletteIndex is { } index && index >= 0 && _paletteStyles.TryGetValue(index, out var style))
            {
                Palette[index] = color;
                style.BackgroundColor = color;
            }
        };

        BrushButton.OnPressed += _ => SelectTool(PdaPainterTool.Brush);
        EraserButton.OnPressed += _ => SelectTool(PdaPainterTool.Eraser);
        PipetteButton.OnPressed += _ => SelectTool(PdaPainterTool.Pipette);

        Size1Button.OnPressed += _ => SelectBrushSize(1);
        Size2Button.OnPressed += _ => SelectBrushSize(2);
        Size3Button.OnPressed += _ => SelectBrushSize(3);

        TemplateList.OnItemSelected += args =>
        {
            if (args.ItemIndex >= 0 && args.ItemIndex < _templateIds.Count)
                SelectTemplate(_templateIds[args.ItemIndex]);
        };

        TemplateSearch.OnTextChanged += args =>
        {
            ApplyTemplateFilter(args.Text);
            _pixels.Clear();
            RefreshCanvases();
        };

        SaveButton.OnPressed += _ =>
        {
            var templateId = Tabs.CurrentTab == 1 ? _selectedTemplate : null;
            OnSavePressed?.Invoke(templateId);
        };

        ResetButton.OnPressed += _ =>
        {
            _pixels.Clear();
            _selectedTemplate = null;
            UpdateTemplateHighlight();
            RefreshCanvases();
            OnResetPressed?.Invoke();
        };

        SelectTool(PdaPainterTool.Brush);
        SelectBrushSize(1);
    }

    public void UpdateState(PdaPainterBoundUserInterfaceState state)
    {
        _pixels.Clear();
        foreach (var (k, v) in state.Canvas)
        {
            _pixels[k] = v;
        }

        _previewProtoId = state.PreviewProtoId;

        PdaNameLabel.Text = state.PreviewName != null
            ? Loc.GetString("pda-painter-inserted", ("name", state.PreviewName))
            : Loc.GetString("pda-painter-no-pda");

        if (!_populated)
        {
            PopulateTemplates(state.Templates);
            _populated = true;
        }

        if (_selectedTemplate == null && state.SelectedTemplate != null)
            _selectedTemplate = state.SelectedTemplate;

        UpdateTemplateHighlight();
        RefreshCanvases();
    }

    private void PopulatePalette()
    {
        for (var i = 0; i < Palette.Length; i++)
        {
            var index = i;
            var button = new Button
            {
                MinSize = new Vector2(56, 32),
            };
            var style = new StyleBoxFlat(Palette[i])
            {
                BorderColor = UnselectedBorder,
                BorderThickness = new Thickness(2),
            };
            button.StyleBoxOverride = style;
            _paletteStyles[index] = style;
            button.OnPressed += _ =>
            {
                _currentColor = Palette[index];
                SelectPaletteIndex(index);
                ColorPicker.Color = Palette[index];
            };
            PaletteGrid.AddChild(button);
            _paletteButtons[index] = button;
        }

        SelectPaletteIndex(0);
    }

    private void PopulateTemplates(List<PdaPainterTemplateInfo> templates)
    {
        _allTemplates.Clear();
        _templateRsi.Clear();
        _templateIcons.Clear();

        foreach (var template in templates)
        {
            var (icon, rsi, spriteState) = ResolvePdaSprite(template.Id);
            _templateRsi[template.Id] = (rsi, spriteState);
            _templateIcons[template.Id] = rsi != null && spriteState != null
                ? LoadBackdrop((null, rsi, spriteState))
                : icon;
            _allTemplates.Add(template);
        }

        ApplyTemplateFilter(TemplateSearch.Text);
    }

    private void ApplyTemplateFilter(string? filter)
    {
        TemplateList.Clear();
        _templateIds.Clear();

        filter = filter?.Trim();
        foreach (var template in _allTemplates)
        {
            if (!string.IsNullOrEmpty(filter) &&
                !template.Name.Contains(filter, StringComparison.InvariantCultureIgnoreCase) &&
                !template.Id.Contains(filter, StringComparison.InvariantCultureIgnoreCase))
            {
                continue;
            }

            TemplateList.AddItem(template.Name, _templateIcons.GetValueOrDefault(template.Id), metadata: template.Id);
            _templateIds.Add(template.Id);
        }

        UpdateTemplateHighlight();
    }

    private (Texture? icon, string? rsi, string? state) ResolvePdaSprite(string protoId)
    {
        if (!_proto.TryIndex<EntityPrototype>(protoId, out var proto) || proto.Abstract)
            return (null, null, null);

        EntityUid? ent = null;

        try
        {
            ent = _entMan.SpawnEntity(protoId, MapCoordinates.Nullspace);

            string? state = null;
            if (_appearance.TryGetData<string>(ent.Value, PdaVisuals.PdaType, out var initState))
                state = initState;

            string? rsi = null;
            if (_entMan.TryGetComponent<SpriteComponent>(ent, out var sprite))
            {
                rsi = sprite.BaseRSI?.Path.ToString();
            }

            Texture? icon = null;
            if (rsi != null && state != null)
            {
                try
                {
                    icon = _spriteSystem.Frame0(new SpriteSpecifier.Rsi(new ResPath(rsi), state));
                }
                catch
                {
                }
            }

            return (icon, rsi, state);
        }
        catch
        {
            return (null, null, null);
        }
        finally
        {
            if (ent != null)
                _entMan.DeleteEntity(ent.Value);
        }
    }

    private void WireCanvas(PdaPainterCanvas canvas)
    {
        canvas.PixelsChanged += (indices, colors) => OnPixelsDrawn?.Invoke(indices, colors);
        canvas.PickedColor += color =>
        {
            _currentColor = color;
            SelectPaletteIndex(-1);
            ColorPicker.Color = color;
        };
    }

    private void SelectTool(PdaPainterTool tool)
    {
        _tool = tool;
        FreeCanvas.Tool = tool;
        TemplateCanvas.Tool = tool;

        BrushButton.Modulate = tool == PdaPainterTool.Brush ? Highlight : Color.White;
        EraserButton.Modulate = tool == PdaPainterTool.Eraser ? Highlight : Color.White;
        PipetteButton.Modulate = tool == PdaPainterTool.Pipette ? Highlight : Color.White;
    }

    private void SelectBrushSize(int size)
    {
        FreeCanvas.BrushSize = size;
        TemplateCanvas.BrushSize = size;

        Size1Button.Modulate = size == 1 ? Highlight : Color.White;
        Size2Button.Modulate = size == 2 ? Highlight : Color.White;
        Size3Button.Modulate = size == 3 ? Highlight : Color.White;
    }

    private void SelectPaletteIndex(int index)
    {
        _selectedPaletteIndex = index;

        foreach (var (i, style) in _paletteStyles)
        {
            style.BorderColor = i == index ? SelectedBorder : UnselectedBorder;
            style.BorderThickness = new Thickness(i == index ? 3 : 2);
        }
    }

    private void SelectTemplate(string templateId)
    {
        if (_selectedTemplate == templateId)
            return;

        _selectedTemplate = templateId;
        _pixels.Clear();
        UpdateTemplateHighlight();
        RefreshCanvases();
    }

    private void UpdateTemplateHighlight()
    {
        for (var i = 0; i < _templateIds.Count; i++)
        {
            TemplateList[i].Selected = _templateIds[i] == _selectedTemplate;
        }
    }

    private void RefreshCanvases()
    {
        var freeResolved = ResolvePdaSprite(_previewProtoId ?? "BasePDA");
        FreeCanvas.Backdrop = LoadBackdrop(freeResolved);
        _previewPixelMap = LoadBackdropPixels(freeResolved.rsi, freeResolved.state);

        var (tRsi, tState) = _selectedTemplate != null && _templateRsi.TryGetValue(_selectedTemplate, out var resolved)
            ? resolved
            : (null, null);
        TemplateCanvas.Backdrop = LoadBackdrop((null, tRsi, tState));
        _templatePixelMap = LoadBackdropPixels(tRsi, tState);

        FreeCanvas.Pixels = _pixels;
        TemplateCanvas.Pixels = _pixels;
        FreeCanvas.ColorProvider = () => _currentColor;
        TemplateCanvas.ColorProvider = () => _currentColor;
        FreeCanvas.PixelSampler = idx => SamplePixelMap(_previewPixelMap, idx);
        TemplateCanvas.PixelSampler = idx => SamplePixelMap(_templatePixelMap, idx);

        FreeCanvas.UpdateDraw();
        TemplateCanvas.UpdateDraw();
    }

    private Color? SamplePixelMap(Dictionary<int, int>? map, int index)
    {
        if (map != null && map.TryGetValue(index, out var packed) && (packed >> 24) != 0)
            return PdaPainterCanvas.UnpackColor(packed);

        return null;
    }

    private Dictionary<int, int>? LoadBackdropPixels(string? rsi, string? state)
    {
        if (rsi == null || state == null)
            return null;

        var key = $"{rsi}#{state}";
        if (_pixelMapCache.TryGetValue(key, out var cached))
            return cached;

        Dictionary<int, int>? map = null;

        foreach (var candidate in new[] { $"{rsi}/{state}.png", $"{rsi}/{state}0.png" })
        {
            var path = new ResPath(candidate.StartsWith("/") ? candidate : $"/Textures/{candidate}");
            if (!_resMan.TryContentFileRead(path, out var stream))
                continue;

            using (stream)
            {
                using var image = SixLabors.ImageSharp.Image.Load<SixLabors.ImageSharp.PixelFormats.Rgba32>(stream);
                var span = image.GetPixelSpan();

                map = new Dictionary<int, int>();
                for (var y = 0; y < PdaPainterCanvas.CanvasSize; y++)
                {
                    for (var x = 0; x < PdaPainterCanvas.CanvasSize; x++)
                    {
                        var sx = Math.Min(image.Width - 1, x * image.Width / PdaPainterCanvas.CanvasSize);
                        var sy = Math.Min(image.Height - 1, y * image.Height / PdaPainterCanvas.CanvasSize);
                        var px = span[sy * image.Width + sx];
                        if (px.A == 0)
                            continue;

                        var packed = (px.A << 24) | (px.R << 16) | (px.G << 8) | px.B;
                        map[y * PdaPainterCanvas.CanvasSize + x] = packed;
                    }
                }
            }

            break;
        }

        _pixelMapCache[key] = map;
        return map;
    }

    private Texture? LoadBackdrop((Texture?, string?, string?) resolved)
    {
        var (_, rsi, state) = resolved;
        if (rsi == null || state == null)
            return null;

        try
        {
            return _spriteSystem.Frame0(new SpriteSpecifier.Rsi(new ResPath(rsi), state));
        }
        catch
        {
            return null;
        }
    }
}
