// TEMP FOR EVENT DONT FCKNG TOUCH
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._DeadSpace.Abductor;

[GenerateTypedNameReferences]
public sealed partial class AbductorConsoleWindow : DefaultWindow
{
    public AbductorConsoleWindow() => RobustXamlLoader.Load(this);
}