using Content.Client.Communications.UI;
using Content.Client.Stylesheets;
using Content.Client.UserInterface.Controls;
using Content.Shared.CCVar;
using Content.Shared.NukeOps;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration;
using Robust.Shared.Timing;
using Robust.Shared.Utility;

namespace Content.Client.DeadSpace.NukeOps.UI;

/// <summary>
/// Communications-console style UI for the declaration-of-war device.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class WarDeclaratorCommsMenu : FancyWindow
{
    [Dependency] private readonly IConfigurationManager _cfg = default!;
    [Dependency] private readonly IGameTiming _gameTiming = default!;
    [Dependency] private readonly ILocalizationManager _localizationManager = default!;

    public event Action<string>? OnActivated;
    public event Action<string, string>? OnSecondaryAnnouncement;

    private TimeSpan _endTime;
    private TimeSpan _shuttleDisabledTime;
    private WarConditionStatus _status;

    private bool _canDeclareWar;
    private bool _secondaryAnnouncementEnabled;

    public WarDeclaratorCommsMenu()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);

        WarMessageInput.Placeholder =
            new Rope.Leaf(_localizationManager.GetString("war-declarator-message-placeholder"));

        SecondaryMessageInput.Placeholder =
            new Rope.Leaf(_localizationManager.GetString("war-declarator-comms-secondary-placeholder"));

        WarMessageInput.OnTextChanged += _ => SyncButtonState();
        SecondaryMessageInput.OnTextChanged += _ => SyncButtonState();
        SecondaryTitleInput.OnTextChanged += _ => SyncButtonState();

        WarButton.OnPressed += _ =>
            OnActivated?.Invoke(Rope.Collapse(WarMessageInput.TextRope));

        SecondaryAnnouncementButton.OnPressed += _ =>
            OnSecondaryAnnouncement?.Invoke(
                SecondaryTitleInput.Text,
                Rope.Collapse(SecondaryMessageInput.TextRope));

        TabContainer.SetTabVisible(SecondaryTab, false);

        SyncButtonState();
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);
        UpdateTimer();
    }

    public void UpdateState(WarDeclaratorBoundUserInterfaceState state)
    {
        _secondaryAnnouncementEnabled = state.SecondaryAnnouncementEnabled;

        TabContainer.SetTabVisible(SecondaryTab, _secondaryAnnouncementEnabled);

        MainTabs.InvalidateMeasure();
        MainTabs.InvalidateArrange();
        InvalidateMeasure();

        if (!_secondaryAnnouncementEnabled && MainTabs.CurrentTab == 1)
            MainTabs.CurrentTab = 0;

        if (state.Status != null)
        {
            _endTime = state.EndTime;
            _shuttleDisabledTime = state.ShuttleDisabledTime;
            _status = state.Status.Value;

            UpdateStatus(state.Status.Value);
        }
        else
        {
            // Keep the standard button available until the first server state arrives.
            _canDeclareWar = true;
        }

        SyncButtonState();
    }

    private void UpdateStatus(WarConditionStatus status)
    {
        switch (status)
        {
            case WarConditionStatus.WarReady:
                _canDeclareWar = false;
                StatusLabel.Text = Loc.GetString("war-declarator-boost-declared");
                StatusLabel.SetOnlyStyleClass(StyleClass.Highlight);
                UpdateTimer();
                break;

            case WarConditionStatus.YesWar:
                _canDeclareWar = true;
                WarButton.Text = Loc.GetString("war-declarator-ui-war-button");
                StatusLabel.Text = Loc.GetString("war-declarator-boost-possible");
                StatusLabel.SetOnlyStyleClass(StyleClass.Positive);
                UpdateTimer();
                break;

            case WarConditionStatus.NoWarSmallCrew:
                // Preserve the original behavior: the client does not disable the button here.
                _canDeclareWar = true;
                StatusLabel.Text = Loc.GetString("war-declarator-boost-impossible");
                InfoLabel.Text = Loc.GetString("war-declarator-conditions-small-crew");
                StatusLabel.SetOnlyStyleClass(StyleClass.Negative);
                break;

            case WarConditionStatus.NoWarUnknown:
            default:
                // The server decides whether war can actually be declared.
                _canDeclareWar = true;
                StatusLabel.Text = Loc.GetString("war-declarator-boost-impossible");
                InfoLabel.Text = Loc.GetString("war-declarator-conditions-unknown");
                StatusLabel.SetOnlyStyleClass(StyleClass.Negative);
                break;
        }
    }

    private void SyncButtonState()
    {
        var maxLength = _cfg.GetCVar(CCVars.ChatMaxAnnouncementLength);

        WarButton.Disabled =
            !_canDeclareWar ||
            WarMessageInput.TextLength > maxLength;

        var secondaryTitle = SecondaryTitleInput.Text.Trim();
        var secondaryText = Rope.Collapse(SecondaryMessageInput.TextRope).Trim();

        SecondaryAnnouncementButton.Disabled =
            !_secondaryAnnouncementEnabled ||
            (string.IsNullOrWhiteSpace(secondaryTitle) && string.IsNullOrWhiteSpace(secondaryText)) ||
            SecondaryTitleInput.Text.Length > maxLength ||
            SecondaryMessageInput.TextLength > maxLength;

        UpdateCharacterLimitLabel(
            WarCharLimitLabel,
            WarMessageInput.TextLength,
            maxLength);

        UpdateCharacterLimitLabel(
            SecondaryCharLimitLabel,
            SecondaryMessageInput.TextLength,
            maxLength);
    }

    private static void UpdateCharacterLimitLabel(Label label, int length, int maximum)
    {
        label.SetOnlyStyleClass(
            length > maximum
                ? CommunicationsConsoleSheetlet.CharLimitExceeded
                : CommunicationsConsoleSheetlet.CharLimit);

        label.Text = Loc.GetString(
            "comms-console-char-limit",
            ("count", length),
            ("max", maximum));
    }

    private void UpdateTimer()
    {
        switch (_status)
        {
            case WarConditionStatus.YesWar:
            {
                var timeLeft = _endTime - _gameTiming.CurTime;
                if (timeLeft > TimeSpan.Zero)
                {
                    InfoLabel.Text = Loc.GetString(
                        "war-declarator-boost-timer",
                        ("time", timeLeft.ToString(@"mm\:ss")));
                }

                break;
            }

            case WarConditionStatus.WarReady:
            {
                var time = _shuttleDisabledTime - _gameTiming.CurTime;
                if (time > TimeSpan.Zero)
                {
                    InfoLabel.Text = Loc.GetString(
                        "war-declarator-boost-timer",
                        ("time", time.ToString(@"mm\:ss")));
                }
                else
                {
                    InfoLabel.Text = Loc.GetString("war-declarator-conditions-ready");
                }

                break;
            }
        }
    }
}
