using System.IO;
using System.Text.RegularExpressions;
using Content.Shared.DeadSpace.Ports.Jukebox;
using Content.Shared.Popups;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration;
using Robust.Shared.Timing;
using Robust.Shared.Utility;

#pragma warning disable RA0026

namespace Content.Client.DeadSpace.Ports.Jukebox;

[GenerateTypedNameReferences]
public sealed partial class TapeCreatorMenu : DefaultWindow
{
    [Dependency] private readonly EntityManager _entityManager = default!;
    [Dependency] private readonly IFileDialogManager _fileDialogManager = default!;
    [Dependency] private readonly IConfigurationManager _cfg = default!;
    [Dependency] private readonly ClientJukeboxSongsSyncManager _songs = default!;
    private readonly SharedPopupSystem _popupSystem = default!;

    private byte[] _songBytes = Array.Empty<byte>();
    private bool _uploading;
    private bool _loading;
    private Entity<TapeCreatorComponent> _entity;

    private const double BytesToMegabytes = 0.000001d;

    public TapeCreatorMenu(Entity<TapeCreatorComponent> entity)
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _popupSystem = _entityManager.System<SharedPopupSystem>();

        _entity = entity;

        LoadSongButton.OnPressed += TryLoadSong;
        UploadSong.OnPressed += OnUploadButtonPressed;
    }

    private async void OnUploadButtonPressed(BaseButton.ButtonEventArgs obj)
    {
        if(!CanUploadSong()) return;

        var input = SongNameField.Text;

        string pattern = @"[^a-zA-Zа-яА-Я ]+";
        string replacement = "";

        var songName = Regex.Replace(input, pattern, replacement);
        songName = Regex.Replace(songName, @"\s+", " ");

        var songBytes = _songBytes;

        var msg = new JukeboxSongUploadRequest()
        {
            SongName = songName,
            SongBytes = songBytes,
            TapeCreatorUid = _entityManager.GetNetEntity(_entity.Owner)
        };

        _uploading = true;
        var uploaded = await _songs.UploadSong(msg);
        _uploading = false;
        if (Disposed)
            return;
        if (!uploaded)
        {
            _popupSystem.PopupEntity("Не удалось передать запись. Попробуйте ещё раз.", _entity.Owner);
            return;
        }
        _songBytes = Array.Empty<byte>();
        SongNameField.Clear();

        _popupSystem.PopupEntity("Внимание. Начинается запись мозговой активности.", _entity.Owner);
    }

    private async void TryLoadSong(BaseButton.ButtonEventArgs obj)
    {
        _loading = true;
        LoadSongButton.Disabled = true;
        try
        {
            var fileFilter = new FileDialogFilters(new FileDialogFilters.Group("ogg"));
            using var file = await _fileDialogManager.OpenFile(fileFilter);
            if (Disposed || file == null)
                return;

            var size = file.Length * BytesToMegabytes;
            var limit = _cfg.GetCVar(JKCVars.MaxJukeboxSongSizeInMB);
            if (size > limit)
            {
                _popupSystem.PopupEntity($"Лимит активности мозговых волн превышен на {size - limit} мегахрюков", _entity.Owner);
                return;
            }

            using var buffer = new MemoryStream();
            await file.CopyToAsync(buffer);
            if (!Disposed)
                _songBytes = buffer.ToArray();
        }
        catch (Exception)
        {
            if (!Disposed)
                _popupSystem.PopupEntity("Не удалось прочитать музыкальный файл.", _entity.Owner);
        }
        finally
        {
            _loading = false;
            if (!Disposed)
                LoadSongButton.Disabled = _uploading;
        }
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        CoinsLabel.Text = _entity.Comp.CoinBalance.ToString();
        LoadSongButton.Disabled = _loading || _uploading;

        if (CanUploadSong())
        {
            UploadSong.Disabled = false;
        }
        else
        {
            UploadSong.Disabled = true;
        }
    }

    private bool CanUploadSong()
    {
        return !_loading && !_uploading && SongNameField.Text.Length > 0 && _songBytes.Length > 0 && _entity.Comp.CoinBalance > 0 && _entity.Comp.InsertedTape.HasValue && !_entity.Comp.Recording;
    }
}
