- type: gameMapPool
  id: DefaultMapPool
  maps:
  # - DSTaipan # not mappool map
  # - Amber # remap in progress
  # - Aspid # remap in progress
  - Bagel
  # - Barratry # remap in progress
  - Box
  - Cluster
  - Cog
  - Convex
  - Core
  - CorvaxAstra
  - CorvaxAvrite
  - CorvaxChloris
  - CorvaxDelta
  - CorvaxGlacier
  # - CorvaxPaper # remap in progress
  - CorvaxSilly
  - CorvaxSpectrum
  - Elkridge
  # - Fland # remap in progress
  - Gate
  - Ishimura
  - Gemini #DS14
  - Loop
  - Marathon
  - Meta
  - Oasis
  - Omega
  # - Origin # remap in progress
  - Packed
  - Plasma 
  - Reach
  # - Exo # map prototype is commented out
  - Saltern
  # - Snowball #DS14
  - Train
