- type: gameMapPool
  id: DefaultMapPool
  maps:
  # - DSTaipan # not mappool map
  - Amber
  # - Aspid # remap in progress
  - Bagel
  - Barratry
  - Box
  - Cluster
  - Cog
  - Convex
  - Core
  - CorvaxAstra
  - CorvaxAvrite
  - CorvaxChloris
  - CorvaxDelta
  - CorvaxGlacier
  # - CorvaxPaper # Removed by Liv
  - CorvaxSilly
  - CorvaxSpectrum
  - Elkridge
  - Fland
  - Gate
  - Ishimura
  - Gemini #DS14
  - Loop
  - Marathon
  - Meta
  - Oasis
  - Omega
  - Origin
  - Packed
  - Plasma 
  - Reach
  # - Exo # map prototype is commented out
  - Saltern
  # - Snowball #DS14
  - Train
