- type: entity
  id: PhotocopierMachineCircuitboard
  parent: BaseMachineCircuitboard
  name: копировальный аппарат (машинная плата)
  description: Из этой машинной платы собирается копировальный аппарат.
  components:
    - type: Sprite
      state: science
    - type: MachineBoard
      prototype: PhotocopierBase
      stackRequirements:
        Plastic : 5
        Steel : 5

- type: entity
  id: CBURNTechFabCircuitboard
  parent: BaseMachineCircuitboard
  name: ЗажигФаб РХБЗЗ (машинная плата)
  description: Печатная плата ЗажигФаба РХБЗЗ.
  components:
    - type: Sprite
      state: security
    - type: MachineBoard
      prototype: CBURNTechFab
      stackRequirements:
        Manipulator: 2
