using Content.Client.Stylesheets;
using Content.Client.UserInterface.Controls;
using Content.Shared.NukeOps;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;
using Robust.Shared.Utility;

namespace Content.Client.NukeOps;

[GenerateTypedNameReferences]
public sealed partial class WarDeclaratorWindow : FancyWindow
{
    [Dependency] private readonly IGameTiming _gameTiming = default!;
    [Dependency] private readonly ILocalizationManager _localizationManager = default!;

    public event Action<string>? OnActivated;

    // DS14-start
    public event Action<string, string>? OnSecondaryAnnouncement;
    // DS14-end

    private TimeSpan _endTime;
    private TimeSpan _shuttleDisabledTime;
    private WarConditionStatus _status;

    public WarDeclaratorWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        WarButton.OnPressed += _ =>
            OnActivated?.Invoke(Rope.Collapse(MessageEdit.TextRope));

        // DS14-start
        SecondaryAnnouncementButton.OnPressed += _ =>
            OnSecondaryAnnouncement?.Invoke(
                SecondaryTitleEdit.Text,
                Rope.Collapse(SecondaryMessageEdit.TextRope));
        // DS14-end

        MessageEdit.Placeholder =
            new Rope.Leaf(_localizationManager.GetString("war-declarator-message-placeholder"));

        // DS14-start
        SecondaryMessageEdit.Placeholder =
            new Rope.Leaf("Подробный текст объявления...");
        // DS14-end
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);
        UpdateTimer();
    }

    public void UpdateState(WarDeclaratorBoundUserInterfaceState state)
    {
        // DS14-start
        SecondaryTabView.Visible = state.SecondaryAnnouncementEnabled;

        if (!state.SecondaryAnnouncementEnabled)
            MainTabs.CurrentTab = 0;
        // DS14-end

        if (state.Status == null)
        {
            // Keep the button available until the first status update,
            // matching the original WarDeclaratorWindow behavior.
            WarButton.Disabled = false;
            return;
        }

        // Original SS14/DS14 behavior:
        // disable the button only after war has been successfully declared.
        WarButton.Disabled = state.Status == WarConditionStatus.WarReady;

        _endTime = state.EndTime;
        _shuttleDisabledTime = state.ShuttleDisabledTime;
        _status = state.Status.Value;

        UpdateStatus(state.Status.Value);
    }

    private void UpdateStatus(WarConditionStatus status)
    {
        switch (status)
        {
            case WarConditionStatus.WarReady:
                WarButton.Disabled = true;
                StatusLabel.Text = Loc.GetString("war-declarator-boost-declared");
                UpdateTimer();
                StatusLabel.SetOnlyStyleClass(StyleClass.Highlight);
                break;

            case WarConditionStatus.YesWar:
                // DS14-start
                WarButton.Disabled = false;
                // DS14-end
                WarButton.Text = Loc.GetString("war-declarator-ui-war-button");
                StatusLabel.Text = Loc.GetString("war-declarator-boost-possible");
                UpdateTimer();
                StatusLabel.SetOnlyStyleClass(StyleClass.Positive);
                break;

            case WarConditionStatus.NoWarSmallCrew:
                // The original window did not disable the button in this state.
                WarButton.Disabled = false;
                StatusLabel.Text = Loc.GetString("war-declarator-boost-impossible");
                InfoLabel.Text = Loc.GetString("war-declarator-conditions-small-crew");
                StatusLabel.SetOnlyStyleClass(StyleClass.Negative);
                break;

            // DS14 no stealth nuke - NoWarShuttleDeparted and NoWarTimeout removed
            case WarConditionStatus.NoWarUnknown:
                // The original window did not disable the button in this state.
                WarButton.Disabled = false;
                StatusLabel.Text = Loc.GetString("war-declarator-boost-impossible");
                InfoLabel.Text = Loc.GetString("war-declarator-conditions-unknown");
                StatusLabel.SetOnlyStyleClass(StyleClass.Negative);
                break;

            default:
                // Do not disable the button for an unknown client-side state.
                WarButton.Disabled = false;
                StatusLabel.Text = Loc.GetString("war-declarator-boost-impossible");
                InfoLabel.Text = Loc.GetString("war-declarator-conditions-unknown");
                StatusLabel.SetOnlyStyleClass(StyleClass.Negative);
                break;
        }
    }

    private void UpdateTimer()
    {
        switch (_status)
        {
            case WarConditionStatus.YesWar:
            {
                var timeLeft = _endTime - _gameTiming.CurTime;
                if (timeLeft > TimeSpan.Zero)
                {
                    InfoLabel.Text = Loc.GetString(
                        "war-declarator-boost-timer",
                        ("time", timeLeft.ToString(@"mm\:ss")));
                }

                break;
            }

            case WarConditionStatus.WarReady:
            {
                var time = _shuttleDisabledTime - _gameTiming.CurTime;
                if (time > TimeSpan.Zero)
                {
                    InfoLabel.Text = Loc.GetString(
                        "war-declarator-boost-timer",
                        ("time", time.ToString(@"mm\:ss")));
                }
                else
                {
                    InfoLabel.Text = Loc.GetString("war-declarator-conditions-ready");
                }

                break;
            }
        }
    }
}
