// Мёртвый Космос, Licensed under custom terms with restrictions on public hosting and commercial use, full text: https://raw.githubusercontent.com/dead-space-server/space-station-14-fobos/master/LICENSE.TXT

using System.Linq;
using Content.Client.UserInterface.Controls;
using Content.Shared.Humanoid;
using Content.Shared.Humanoid.Prototypes;
using Content.Shared.DeadSpace.MedicalRecords;
using Content.Shared.StationRecords;
using Content.Shared.StatusIcon;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;

namespace Content.Client.DeadSpace.MedicalRecords;

/// <summary>
/// Medical Records console window - structure mirrors <c>PersonnelRecordsConsoleWindow</c>.
/// </summary>
/// 
/// <summary>
/// Button availability comes from the server-computed flags in <c>MedicalRecordsConsoleState</c>.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class MedicalRecordsConsoleWindow : FancyWindow
{
    [Dependency] private readonly IEntityManager _entManager = default!;
    [Dependency] private readonly IPrototypeManager _proto = default!;

    private readonly SpriteSystem _spriteSystem;

    private readonly uint _maxLength;
    private uint? _selectedKey;
    private MedicalRecord? _selectedRecord;
    private int? _selectedCase;

    private MedicalCaseWindow? _caseWindow;

    private StationRecordFilterType _currentFilterType;
    private MedicalStatus _currentCrewListFilter;

    private bool _canEdit;
    private bool _canDelete;
    private bool _canPrint;

    public Action<uint?>? OnKeySelected;
    public Action<StationRecordFilterType, string>? OnFiltersChanged;
    public Action<MedicalStatus>? OnStatusFilterPressed;
    public Action<MedicalStatus>? OnStatusChange;
    public Action<MedicalCaseDraft>? OnCaseAdded;
    public Action<int, MedicalCaseDraft>? OnCaseEdited;
    public Action<int>? OnCaseDeleted;
    public Action<int>? OnCasePrinted;

    public MedicalRecordsConsoleWindow(uint maxLength)
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _spriteSystem = _entManager.System<SpriteSystem>();

        _maxLength = maxLength;
        _currentFilterType = StationRecordFilterType.Name;
        _currentCrewListFilter = MedicalStatus.None;

        OpenCentered();

        foreach (var item in Enum.GetValues<StationRecordFilterType>())
        {
            FilterType.AddItem(GetTypeFilterLocals(item), (int) item);
        }

        foreach (var item in Enum.GetValues<MedicalStatus>())
        {
            CrewListFilter.AddItem(GetCrewListFilterLocals(item), (int) item);
        }

        OnClose += () => _caseWindow?.Close();

        RecordListing.OnItemSelected += args =>
        {
            if (RecordListing[args.ItemIndex].Metadata is not uint cast)
                return;

            OnKeySelected?.Invoke(cast);
        };

        RecordListing.OnItemDeselected += _ => OnKeySelected?.Invoke(null);

        FilterType.OnItemSelected += eventArgs =>
        {
            var type = (StationRecordFilterType) eventArgs.Id;

            if (_currentFilterType != type)
            {
                _currentFilterType = type;
                FilterListingOfRecords(FilterText.Text);
            }
        };

        CrewListFilter.OnItemSelected += eventArgs =>
        {
            var type = (MedicalStatus) eventArgs.Id;

            if (_currentCrewListFilter != type)
            {
                _currentCrewListFilter = type;
                OnStatusFilterPressed?.Invoke(type);
            }
        };

        FilterText.OnTextEntered += args => FilterListingOfRecords(args.Text);

        StatusNoneButton.OnPressed += _ => OnStatusChange?.Invoke(MedicalStatus.None);
        StatusOnTreatmentButton.OnPressed += _ => OnStatusChange?.Invoke(MedicalStatus.OnTreatment);
        StatusPsychButton.OnPressed += _ => OnStatusChange?.Invoke(MedicalStatus.PsychUnstable);
        StatusCompletedButton.OnPressed += _ => OnStatusChange?.Invoke(MedicalStatus.CompletedTreatment);

        AddCaseButton.OnPressed += _ => OpenCaseWindow(null);
        EditCaseButton.OnPressed += _ => OpenCaseWindow(_selectedCase);
        DeleteCaseButton.OnPressed += _ =>
        {
            if (_selectedCase is { } index)
                OnCaseDeleted?.Invoke(index);
        };
        PrintCaseButton.OnPressed += _ =>
        {
            if (_selectedCase is { } index)
                OnCasePrinted?.Invoke(index);
        };

        History.OnItemSelected += args =>
        {
            if (History[args.ItemIndex].Metadata is not int index)
            {
                _selectedCase = null;
                CaseDetails.Visible = false;
                UpdateCaseButtons();
                return;
            }

            _selectedCase = index;
            UpdateCaseDetails();
            UpdateCaseButtons();
        };
    }

    public void UpdateState(MedicalRecordsConsoleState state)
    {
        if (state.Filter != null)
        {
            if (state.Filter.Type != _currentFilterType)
                _currentFilterType = state.Filter.Type;

            if (state.Filter.Value != FilterText.Text)
                FilterText.Text = state.Filter.Value;
        }

        if (state.FilterStatus != _currentCrewListFilter)
            _currentCrewListFilter = state.FilterStatus;

        _selectedKey = state.SelectedKey;
        _canEdit = state.CanEdit;
        _canDelete = state.CanDelete;
        _canPrint = state.CanPrint;
        FilterType.SelectId((int) _currentFilterType);
        CrewListFilter.SelectId((int) _currentCrewListFilter);

        var hasListing = state.RecordListing is { Count: > 0 };
        NoRecords.Visible = !hasListing;
        PopulateRecordListing(state.RecordListing);

        var selected = _selectedKey != null;
        PatientContainer.Visible = selected;
        RecordUnselected.Visible = !selected;

        if (state is { StationRecord: not null, MedicalRecord: not null })
        {
            PopulatePatientCard(state.StationRecord, state.MedicalRecord);
            PopulateHistory(state.MedicalRecord);
            _selectedRecord = state.MedicalRecord;
        }
        else
        {
            _selectedRecord = null;
            _selectedCase = null;
            History.Clear();
            NoHistory.Visible = true;
            CaseDetails.Visible = false;
        }

        AddCaseButton.Disabled = !_canEdit || _selectedRecord == null;
        StatusNoneButton.Disabled = !_canEdit;
        StatusOnTreatmentButton.Disabled = !_canEdit;
        StatusPsychButton.Disabled = !_canEdit;
        StatusCompletedButton.Disabled = !_canEdit;

        UpdateCaseButtons();
    }

    private void PopulateRecordListing(Dictionary<uint, string>? listing)
    {
        if (listing == null)
        {
            RecordListing.Clear();
            return;
        }

        var entries = listing.Select(i => new ItemList.Item(RecordListing)
        {
            Text = i.Value,
            Metadata = i.Key,
        }).ToList();
        entries.Sort((a, b) => string.Compare(a.Text, b.Text, StringComparison.Ordinal));
        RecordListing.SetItems(entries, (a, b) => string.Compare(a.Text, b.Text));
    }

    private void PopulatePatientCard(GeneralStationRecord stationRecord, MedicalRecord medicalRecord)
    {
        var na = Loc.GetString("generic-not-available-shorthand");

        PatientName.Text = stationRecord.Name;
        PatientJob.Text = stationRecord.JobTitle ?? na;

        if (_proto.TryIndex<JobIconPrototype>(stationRecord.JobIcon, out var jobIcon))
            PatientJobIcon.Texture = _spriteSystem.Frame0(jobIcon.Icon);

        PatientAge.Text = Loc.GetString("general-station-record-console-record-age", ("age", stationRecord.Age));
        PatientSpecies.Text = Loc.GetString("general-station-record-console-record-species", ("species", GetSpeciesName(stationRecord.Species)));

        PatientSex.Text = Loc.GetString("medical-records-console-record-sex", ("sex", Loc.GetString(SexKey(medicalRecord.Sex))));
        PatientDna.Text = Loc.GetString("medical-records-console-record-dna", ("dna", stationRecord.DNA ?? na));

        PatientStatus.Text = Loc.GetString($"medical-records-status-{medicalRecord.Status.ToString().ToLower()}");
    }

    private void PopulateHistory(MedicalRecord record)
    {
        History.Clear();
        NoHistory.Visible = record.History.Count == 0;

        for (var i = 0; i < record.History.Count; i++)
        {
            var entry = record.History[i];
            var kind = Loc.GetString($"medical-records-case-kind-{entry.Kind.ToString().ToLower()}");
            var flags = string.Empty;

            if (entry.NeedsForcedTreatment)
                flags += $" [{Loc.GetString("medical-records-case-flag-forced")}]";
            if (entry.NeedsContinuedTreatment)
                flags += $" [{Loc.GetString("medical-records-case-flag-continued")}]";
            if (!entry.Open)
                flags += $" [{Loc.GetString("medical-records-case-flag-closed")}]";

            var line = string.IsNullOrWhiteSpace(entry.Diagnosis)
                ? kind
                : $"{kind}: {entry.Diagnosis}";

            History.AddItem($"{line}{flags}", metadata: i);
        }

        // The record may have shrunk under the user's cursor (someone else deleted a case, or a
        // case was closed and the list re-sorted), so only keep the selection if it's still valid.
        if (_selectedCase is { } selected && selected >= record.History.Count)
        {
            _selectedCase = null;
            CaseDetails.Visible = false;
        }
        else if (_selectedCase is { } keep)
        {
            // ItemList has no public Select(index) - setting the item's own Selected property is the
            // supported way to re-highlight it, and it raises OnItemSelected so the details panel
            // comes back with it.
            History[keep].Selected = true;
        }

        UpdateCaseButtons();
    }

    private void UpdateCaseDetails()
    {
        if (_selectedRecord is not { } record || _selectedCase is not { } index || index >= record.History.Count)
        {
            CaseDetails.Visible = false;
            return;
        }

        var entry = record.History[index];
        var message = FormattedMessage.FromMarkupOrThrow(Loc.GetString("medical-records-console-case-details",
            ("diagnosis", FormattedMessage.EscapeText(entry.Diagnosis)),
            ("admission", FormattedMessage.EscapeText(entry.AdmissionState)),
            ("treatment", FormattedMessage.EscapeText(entry.Treatment)),
            ("recommendations", FormattedMessage.EscapeText(entry.Recommendations)),
            ("discharge", FormattedMessage.EscapeText(entry.DischargeState)),
            ("specialists", entry.Specialists.Count == 0
                ? Loc.GetString("medical-records-print-none")
                : FormattedMessage.EscapeText(string.Join(", ", entry.Specialists))),
            ("author", FormattedMessage.EscapeText(entry.AuthorName ?? Loc.GetString("medical-records-case-no-author")))));

        CaseDetails.SetMessage(message);
        CaseDetails.Visible = true;
    }

    private void UpdateCaseButtons()
    {
        var hasSelection = _selectedCase != null;

        EditCaseButton.Disabled = !_canEdit || _selectedRecord == null || !hasSelection;
        PrintCaseButton.Disabled = !_canPrint || !hasSelection;
        DeleteCaseButton.Disabled = !_canDelete || _selectedRecord == null || !hasSelection;
    }

    private void OpenCaseWindow(int? index)
    {
        if (_caseWindow != null)
        {
            _caseWindow.MoveToFront();
            return;
        }

        _caseWindow = new MedicalCaseWindow(_maxLength);

        if (index is { } existing && _selectedRecord is { } record && existing < record.History.Count)
            _caseWindow.SetExisting(existing, record.History[existing]);

        _caseWindow.OnConfirmed += (caseIndex, draft) =>
        {
            if (caseIndex is { } editIndex)
                OnCaseEdited?.Invoke(editIndex, draft);
            else
                OnCaseAdded?.Invoke(draft);
        };

        _caseWindow.OnClose += () => _caseWindow = null;
        _caseWindow.OpenCentered();
    }

    private void FilterListingOfRecords(string text = "")
    {
        OnFiltersChanged?.Invoke(_currentFilterType, text);
    }

    private static string SexKey(Sex sex) => sex switch
    {
        Sex.Male => "medical-records-sex-male",
        Sex.Female => "medical-records-sex-female",
        _ => "medical-records-sex-unsexed",
    };

    private string GetSpeciesName(string species)
    {
        if (_proto.TryIndex<SpeciesPrototype>(species, out var prototype))
            return Loc.GetString(prototype.Name);

        return Loc.GetString("generic-not-available-shorthand");
    }

    private string GetTypeFilterLocals(StationRecordFilterType type) =>
        Loc.GetString($"medical-records-{type.ToString().ToLower()}-filter");

    private string GetCrewListFilterLocals(MedicalStatus type) => type == MedicalStatus.None
        ? Loc.GetString("medical-records-console-show-all")
        : Loc.GetString($"medical-records-status-{type.ToString().ToLower()}");
}
