// Мёртвый Космос, Licensed under custom terms with restrictions on public hosting and commercial use, full text: https://raw.githubusercontent.com/dead-space-server/space-station-14-fobos/master/LICENSE.TXT

using Content.Client.UserInterface.Controls;
using Content.Shared.DeadSpace.MedicalRecords;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.DeadSpace.MedicalRecords;

/// <summary>
/// Add/edit form for a single <see cref="MedicalCase"/>.
/// </summary>
/// 
/// <summary>
/// One window for both operations: an edit is an add with the previous values pre-filled.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class MedicalCaseWindow : FancyWindow
{
    private readonly uint _maxLength;

    private int? _editingIndex;

    public event Action<int?, MedicalCaseDraft>? OnConfirmed;

    public MedicalCaseWindow(uint maxLength)
    {
        RobustXamlLoader.Load(this);

        _maxLength = maxLength;

        CancelButton.OnPressed += _ => Close();
        ConfirmButton.OnPressed += _ => Confirm();
    }

    public void SetExisting(int index, MedicalCase existing)
    {
        Title = Loc.GetString("medical-records-case-window-title-edit");

        CloseCase.Visible = true;
        // The checkbox is "closed", so it starts ticked for an already-closed case and clear for an
        // open one. Leaving it at its default would invert the meaning of the next edit.
        CloseCase.Pressed = !existing.Open;

        AdmissionState.Text = existing.AdmissionState;
        Diagnosis.Text = existing.Diagnosis;
        Treatment.Text = existing.Treatment;
        ContinuedTreatment.Pressed = existing.NeedsContinuedTreatment;
        ForcedTreatment.Pressed = existing.NeedsForcedTreatment;
        Specialists.Text = string.Join(", ", existing.Specialists);
        Recommendations.Text = existing.Recommendations;
        DischargeState.Text = existing.DischargeState;

        _editingIndex = index;
    }

    private void Confirm()
    {
        // The server rejects a blank diagnosis too, but flagging it here stops the user from losing
        // everything they typed to a silent no-op.
        if (string.IsNullOrWhiteSpace(Diagnosis.Text))
        {
            ErrorLabel.Visible = true;
            return;
        }

        OnConfirmed?.Invoke(_editingIndex, new MedicalCaseDraft(
            Clip(AdmissionState.Text),
            Clip(Diagnosis.Text),
            Clip(Treatment.Text),
            ContinuedTreatment.Pressed,
            ForcedTreatment.Pressed,
            ParseSpecialists(Specialists.Text),
            Clip(Recommendations.Text),
            Clip(DischargeState.Text),
            !CloseCase.Pressed));

        // A confirmed edit has been handed to the server; keeping the window up would let the user
        // confirm the same case twice against a stale index.
        Close();
    }

    private string Clip(string input)
    {
        var trimmed = input.Trim();

        return trimmed.Length > _maxLength ? trimmed[..(int) _maxLength] : trimmed;
    }

    private List<string> ParseSpecialists(string text)
    {
        var result = new List<string>();

        if (string.IsNullOrWhiteSpace(text))
            return result;

        foreach (var part in text.Split(','))
        {
            var name = part.Trim();
            if (name.Length > 0)
                result.Add(name);
        }

        return result;
    }
}

/// <summary>
/// Flat bag of case fields, so the window doesn't have to hand a half-mutated
/// <see cref="MedicalCase"/> back to the caller.
/// </summary>
public readonly record struct MedicalCaseDraft(
    string AdmissionState,
    string Diagnosis,
    string Treatment,
    bool NeedsContinuedTreatment,
    bool NeedsForcedTreatment,
    List<string> Specialists,
    string Recommendations,
    string DischargeState,
    bool Open);
