using Content.Client.Administration.Managers;
// DS14-start
using Content.Client.DeadSpace.Administration;
// DS14-end
using Content.Shared.Administration;
using Content.Shared.DeadSpace.Administration.Events;
using Robust.Client.AutoGenerated;
using Robust.Client.Console;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.GameObjects;

namespace Content.Client.Administration.UI.Tabs
{
    [GenerateTypedNameReferences]
    public sealed partial class RoundTab : Control
    {
        [Dependency] private readonly IClientConsoleHost _console = default!;
        [Dependency] private readonly IClientAdminManager _admin = default!;

        // DS14-start
        [Dependency] private readonly IEntityManager _entityManager = default!;

        private SecondaryAnnouncementAdminSystem _secondaryAnnouncements = default!;
        private bool _updatingSecondaryAnnouncements;
        // DS14-end

        public RoundTab()
        {
            RobustXamlLoader.Load(this);
            IoCManager.InjectDependencies(this);

            // DS14-start
            _secondaryAnnouncements = _entityManager.System<SecondaryAnnouncementAdminSystem>();
            _secondaryAnnouncements.StateChanged += OnSecondaryAnnouncementsStateChanged;
            SecondaryAnnouncementsToggle.OnPressed += _ => OnSecondaryAnnouncementsPressed();
            // DS14-end

            StartRound.OnPressed += _ => _console.ExecuteCommand("startround");
            EndRound.OnPressed += _ => _console.ExecuteCommand("endround");
            RestartRound.OnPressed += _ => _console.ExecuteCommand("restartround");
            RestartRoundNow.OnPressed += _ => _console.ExecuteCommand("restartroundnow");
            CentCommTransferButton.OnPressed += _ =>
            {
                if (_admin.HasFlag(AdminFlags.Fun))
                    _console.ExecuteCommand("centcomm_transfer");
            };
            _admin.AdminStatusUpdated += RefreshTransferButton;
            RefreshTransferButton();

            // DS14-start
            RefreshSecondaryAnnouncementsControl();
            // DS14-end
        }

        private void RefreshTransferButton()
        {
            CentCommTransferButton.Visible = _admin.HasFlag(AdminFlags.Fun);
            CentCommTransferButton.Disabled = !_admin.HasFlag(AdminFlags.Fun);

            // DS14-start
            RefreshSecondaryAnnouncementsControl();
            // DS14-end
        }

        // DS14-start
        private void RefreshSecondaryAnnouncementsControl()
        {
            var canControl = _admin.HasFlag(AdminFlags.Round);
            SecondaryAnnouncementsToggle.Visible = canControl;

            if (!canControl)
            {
                SecondaryAnnouncementsToggle.Disabled = true;
                return;
            }

            if (_secondaryAnnouncements.Enabled is { } enabled)
            {
                ApplySecondaryAnnouncementsState(enabled);
            }
            else
            {
                SecondaryAnnouncementsToggle.Disabled = true;
            }

            _secondaryAnnouncements.RequestState();
        }

        private void OnSecondaryAnnouncementsPressed()
        {
            if (_updatingSecondaryAnnouncements || !_admin.HasFlag(AdminFlags.Round))
                return;

            SecondaryAnnouncementsToggle.Disabled = true;
            _secondaryAnnouncements.SetEnabled(SecondaryAnnouncementsToggle.Pressed);
        }

        private void OnSecondaryAnnouncementsStateChanged(bool enabled)
        {
            ApplySecondaryAnnouncementsState(enabled);
        }

        private void ApplySecondaryAnnouncementsState(bool enabled)
        {
            _updatingSecondaryAnnouncements = true;
            SecondaryAnnouncementsToggle.Pressed = enabled;
            SecondaryAnnouncementsToggle.Disabled = !_admin.HasFlag(AdminFlags.Round);
            _updatingSecondaryAnnouncements = false;
        }
        // DS14-end

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                _admin.AdminStatusUpdated -= RefreshTransferButton;

                // DS14-start
                _secondaryAnnouncements.StateChanged -= OnSecondaryAnnouncementsStateChanged;
                // DS14-end
            }

            base.Dispose(disposing);
        }

        // DS14-start
        public void UpdateAutoMapVoteState(AutoMapVoteAdminState? state)
        {
            AutoMapVoteControl.UpdateState(state);
        }
        // DS14-end
    }
}
